version: "3.9"
services:
  postgres:
    image : postgres:12-alpine
    environment:
      - POSTGRES_USER=younes
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=natours
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://younes:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: ["/app/main"]
