// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateLocation(ctx context.Context, arg CreateLocationParams) (Location, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateStartLocation(ctx context.Context, arg CreateStartLocationParams) (StartLocation, error)
	CreateTour(ctx context.Context, arg CreateTourParams) (Tour, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBooking(ctx context.Context, arg DeleteBookingParams) error
	DeleteLocation(ctx context.Context, id int64) error
	DeleteReview(ctx context.Context, id int64) error
	DeleteStartLocation(ctx context.Context, id int64) error
	DeleteTour(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAllBooking(ctx context.Context) ([]Booking, error)
	GetAllLocation(ctx context.Context, limit int32) ([]Location, error)
	GetAllReviews(ctx context.Context) ([]Review, error)
	GetAllTours(ctx context.Context, limit int32) ([]Tour, error)
	GetAllUsers(ctx context.Context, limit int32) ([]GetAllUsersRow, error)
	GetBookingByTourAndUser(ctx context.Context, arg GetBookingByTourAndUserParams) ([]Booking, error)
	GetLocationByID(ctx context.Context, id int64) (Location, error)
	GetReviewByID(ctx context.Context, id int64) (Review, error)
	GetStartLocationByID(ctx context.Context, id int64) (StartLocation, error)
	GetTourByID(ctx context.Context, id int64) (Tour, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	UpdateBooking(ctx context.Context, arg UpdateBookingParams) error
	UpdateLocation(ctx context.Context, arg UpdateLocationParams) error
	UpdateReview(ctx context.Context, arg UpdateReviewParams) error
	UpdateStartLocation(ctx context.Context, arg UpdateStartLocationParams) error
	UpdateTour(ctx context.Context, arg UpdateTourParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
